# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.0601249  0.1322197  0.74015383 ... 0.18649302 0.73230273 0.1776223 ]
 [0.96483791 0.72815776 0.75993378 ... 0.16903125 0.9804337  0.77915026]
 [0.69435151 0.43933829 0.40824706 ... 0.361058   0.24044668 0.58555764]
 ...
 [0.09022202 0.68498906 0.34381181 ... 0.93705687 0.84990982 0.54920608]
 [0.26149461 0.30146822 0.86629044 ... 0.17192669 0.92157678 0.46465517]
 [0.79230843 0.40785795 0.33004078 ... 0.32993793 0.0297588  0.57853094]]
[[0.20717379 0.1006351  0.58456781 ... 0.29243006 0.72005515 0.87485747]
 [0.22918801 0.52653311 0.43028607 ... 0.11770445 0.91986578 0.95885352]
 [0.89152644 0.0930533  0.73859988 ... 0.73604286 0.10002979 0.92315162]
 ...
 [0.20682292 0.81522596 0.43430944 ... 0.97426898 0.96152186 0.0014371 ]
 [0.76391525 0.62333701 0.94450852 ... 0.99347575 0.98155309 0.11341241]
 [0.22698963 0.21429995 0.64929543 ... 0.92546069 0.24226706 0.95385652]]


Без использования numpy

In [18]:
def mult(a, b):
    rowsA = len(a)
    columnsA = len(a[0])
    columnsB = len(b[0])
    result = [[0 for _ in range(columnsB)] for _ in range(rowsA)]
    for i in range(rowsA):
        for j in range(columnsB):
            for k in range(columnsA):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [19]:
def np_mult(a, b):
    result = np.matmul(a, b)
    return result

In [9]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 688 ms, sys: 0 ns, total: 688 ms
Wall time: 691 ms


In [20]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 299 µs, sys: 1.08 ms, total: 1.38 ms
Wall time: 1.28 ms


In [21]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.523758896837535e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [22]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.52968746 0.71853273 0.49663921] [0.67240392 0.47255087 0.47775179]


In [23]:
def scalar_product(a,b):
    s = sum([a[i] * b[i] for i in range(len(a))])
    return s

In [24]:
def np_scalar_product(a,b):
    s = np.dot(a,b)
    return s

In [25]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 22 µs, sys: 4 µs, total: 26 µs
Wall time: 43.9 µs
CPU times: user 0 ns, sys: 149 µs, total: 149 µs
Wall time: 371 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** библиотека NumPy написана на языке С, который выполняет алгоритмы в несколько раз быстрее и эфективнее, чем python. Более того, алгоритмы, используемые в этой библиотеке, очень хорошо оптимизированы.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [26]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = sum([i for i in np.diag(a) if i % 2 == 0])
  return res

In [27]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[3, 6, 3, 8, 8],
       [4, 1, 2, 9, 3],
       [5, 2, 6, 4, 3],
       [8, 4, 5, 5, 3],
       [2, 9, 6, 4, 7]])

In [28]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 64 µs, sys: 0 ns, total: 64 µs
Wall time: 68.4 µs


6

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [67]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    s = np.cumsum(A)
    n = np.arange(1, A.shape[0] + 1)
    result = s / n.reshape(1, -1)
    return result

In [68]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.8922844  0.79497079 0.99150527 0.92675721 0.35563072 0.37110895
 0.66679091 0.38833327 0.72662743 0.4736059  0.84175998 0.99954639
 0.23863023 0.52197378 0.90211705 0.74218508 0.38606261 0.96433069
 0.41202246 0.57866654 0.43567429 0.53222089 0.48199102 0.60707484
 0.25030604 0.28335794 0.73906446 0.19166577 0.52710735 0.58487566
 0.85495147 0.55221544 0.1727926  0.60347228 0.04713579 0.61059868
 0.58213424 0.75659995 0.13162549 0.03955335 0.60412597 0.81401336
 0.57369463 0.67667788 0.1457604  0.82940149 0.69929319 0.89691298
 0.07520734 0.86891057 0.92551542 0.4547086  0.5885133  0.08904093
 0.27491391 0.00449118 0.86899932 0.87389455 0.7763288  0.56422855
 0.79272769 0.85930718 0.35234935 0.57283287 0.69643339 0.15982022
 0.56733266 0.22501831 0.92984148 0.30836799 0.50247697 0.18747339
 0.58571933 0.17346064 0.26444753 0.3356402  0.59717746 0.99716369
 0.05135495 0.22591673 0.95453743 0.69343027 0.89788874 0.08725715
 0.75729242 0.54939142 0.58990532 0.84745581 0.0360812  0.5540

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [69]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    elements = []
    counts = []
    currentElement = a[0]
    currentCount = 1
    for i in range(1, len(a)):
        if a[i] != currentElement:
          elements.append(currentElement)
          currentElement = a[i]
          counts.append(currentCount)
          currentCount = 1
        else:
          currentCount += 1
    elements.append(currentElement)
    counts.append(currentCount)
    result = np.array(elements), np.array(counts)
    return result

In [70]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 32 µs, sys: 6 µs, total: 38 µs
Wall time: 40.5 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [71]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    copyX = np.copy(X)
    copyX[1::2] = a
    copyX[::2] = copyX[::2] ** 3
    reversedCopyX = np.flip(copyX)
    result = np.concatenate((X, reversedCopyX))
    return result

In [72]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 120 µs, sys: 0 ns, total: 120 µs
Wall time: 126 µs
